import NavButton from 'components/NavButton'
import Head from 'next/head'
import tw, { css } from 'twin.macro'
import Image from 'next/image'

const navButtons = [
  { label: 'Report', path: '/report', icon: null },
  { label: 'Send email', path: '/sendemail', icon: null },
  { label: 'Billing page', path: '/billing', icon: null },
]
export default function Layout({ children }) {
  const menuItemStyles = css`
    ${tw`block py-1 md:py-3 pl-4 align-middle no-underline hover:`}
    &:hover {
      ${tw`bg-green-50 border-r-4 border-green-400`}
    }
  `

  const menuItemTextStyles = css`
  pb-1 md:pb-0 text-xs md:text-base block md:inline-block
  `

  return (
    <div>
      <Head>
        <title>Usage report</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div css={[tw`flex flex-col md:flex-row`]}>
          <div css={[tw`h-16 md:h-screen md:w-52`, tw`shadow-xl`]}>
            <div className="flex h-16 justify-between items-center">
              <div className="flex flex-row p-2 md:p-4">
                <Image
                  loader={({ src }) => `https://cdn.simplesat.io/images/${src}?size=32x32`}
                  alt="logo"
                  width="40"
                  height="40"
                  className="!h-8 !w-8 !p-1"
                  src="simplesat-logomark-green-small.png"
                />
                <div className="ml-2">
                  <p className="text-bold font-bold">Hackathon Q2</p>
                  <p className="text-xs text-gray-500">Simplesat</p>
                </div>
              </div>
              <a href="#" css={tw`md:hidden pr-2`}>
                <span css={menuItemTextStyles}>Sign out</span>
              </a>
            </div>

            <ul
              css={[
                tw`hidden md:flex flex-row md:flex-col text-left`,
                tw`py-0 md:py-3 px-1 md:px-2 `,
              ]}
            >
              {navButtons.map((nav) => (
                <li className="mr-3 flex-1" key={nav.label}>
                  <NavButton label={nav.label} path={nav.path} icon={nav.icon} />
                </li>
              ))}

              <li className="mr-3 flex-1">
                <a href="#" css={[menuItemStyles]}>
                  <span css={menuItemTextStyles}>Sign out</span>
                </a>
              </li>
            </ul>
          </div>
          <div className="flex-1 p-5">{children}</div>
        </div>
      </main>

      <footer></footer>
    </div>
  )
}
