import firebase from 'firebase'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import Link from 'next/link'
import tw, { css } from 'twin.macro'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope, faReceipt, faSignOut } from '@fortawesome/pro-solid-svg-icons'

import NavButton from 'components/NavButton'

export default function Layout({ children }) {
  const router = useRouter()
  return (
    <div>
      <Head>
        <title>Usage report</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div css={[tw`flex flex-col md:flex-row`]}>
          <div css={[tw`h-16 md:h-screen md:w-52`, tw`shadow-xl`]}>
            <div className="flex h-16 justify-between items-center">
              <div className="flex flex-row p-2 md:p-4">
                <Image
                  loader={({ src }) => `https://cdn.simplesat.io/images/${src}?size=32x32`}
                  alt="logo"
                  width="40"
                  height="40"
                  className="!h-8 !w-8 !p-1"
                  src="simplesat-logomark-green-small.png"
                />
                <div className="ml-2">
                  <p className="text-bold font-bold">Hackathon Q2</p>
                  <p className="text-xs text-gray-500">Simplesat</p>
                </div>
              </div>
              <a href="#" css={tw`md:hidden pr-2`}>
                <span css={menuItemTextStyles}>Sign out</span>
              </a>
            </div>

            <ul
              css={[
                tw`hidden md:flex flex-row md:flex-col text-left`,
                tw`py-0 md:py-3 px-1 md:px-2 `,
              ]}
            >
              {navButtons.map((nav) => (
                <li className="mr-3 flex-1" key={nav.path}>
                  <Link href={nav.path} passHref>
                    <NavButton isActive={nav.path === router.pathname}>{nav.label}</NavButton>
                  </Link>
                </li>
              ))}

              <li className="mr-3 flex-1">
                <NavButton
                  onClick={(e) => {
                    e.preventDefault()
                    router.push('/login')
                    firebase.auth().signOut()
                  }}
                >
                  <FontAwesomeIcon icon={faSignOut} tw="w-4 mr-2" />
                  Sign out
                </NavButton>
              </li>
            </ul>
          </div>
          <div className="flex-1 p-10">{children}</div>
        </div>
      </main>

      <footer></footer>
    </div>
  )
}

const menuItemTextStyles = css`
  ${tw`!ml-2 pb-1 md:pb-0 text-xs md:text-base block md:inline-block`}
`

const navButtons = [
  {
    label: (
      <>
        <FontAwesomeIcon icon={faReceipt} tw="w-4 mr-2" />
        Billing page
      </>
    ),
    path: '/billing',
  },
  {
    label: (
      <>
        <FontAwesomeIcon icon={faEnvelope} tw="w-4 mr-2" />
        Send email
      </>
    ),
    path: '/sendEmail',
  },
]
